### ISSUE TITLE
v2.0

### ISSUE THREAD

**Issue by WardsParadox** [munkireport/munkireport#1] opened 2019-07-05 20:47 UTC
When a client submits to the processor, an error reports:
syntax error, unexpected in <b>/munkireport_processor</b> on line 72

**Comment by bochoven** [comment] 2019-07-05 20:51
Did you update the munkireport module?

**Comment by WardsParadox** [comment] 2019-07-05 20:52
Yes, it's on v2.0 now.

**Comment by bochoven** [comment] 2019-07-05 20:57
Can't reproduce the issue.. You're not including another version of the module?

**Comment by bochoven** [comment] 2019-07-06 09:25
Should be fixed with 66d2df4

**Closed by bochoven** 2019-07-06 09:25 UTC
